### ISSUE TITLE
Build + merge successful but not updating on conda-forge

### ISSUE THREAD

**Issue by ksamuk** [conda-forge/pixy-feedstock#61]
### General comment:

Hi There,

@conda-forge/staged-recipes

Apologies if this is the wrong place, but I maintain the software pixy here: https://anaconda.org/conda-forge/pixy, which usually has auto-posted new versions to conda-forge after a successful pull request + CI test + merge on the feedstock here: https://github.com/conda-forge/pixy-feedstock. Recently, it seems that new versions are passing tests, but after the merge, a new versions of the package is no longer posting to conda-forge. 

The main thing I've changed recently was an attempt to get macOS arm support, but I'm not sure why this would block the update. Any ideas would be greatly appreciate, thanks very much!

**Comment by jakirkham** [comment]
That is because re-rendering in commit ( https://github.com/conda-forge/pixy-feedstock/pull/59/commits/7c25c356bae5fb61e42c99b4e005729ca58862ca ) removed all the CI files

Likely this is due to a bug in the `skip` syntax

https://github.com/conda-forge/pixy-feedstock/blob/7c711f100a9185f681c50189446be71db0749fbb/recipe/meta.yaml#L16

**Comment by jakirkham** [comment]
Also noticing that pre-release builds are being uploaded by this feedstock. Please read over [CFEP 5]( https://github.com/conda-forge/cfep/blob/2409812d68296fcf2e06255687cc7cb085923ffd/cfep-05.md ), which provides a policy for doing this. Would recommend making those updates here. Please let us know if you have any questions on that. Thanks!

**Comment by jakirkham** [comment]
cc @conda-forge/core

**Comment by jaimergp** [comment]
See https://github.com/conda-forge/pixy-feedstock/pull/62

**Comment by ksamuk** [comment]
Amazing, thank you so much!
